### PR TITLE
Use secure CRAN mirror

### PR DESCRIPTION
**Pull request by csgillespie**
A simple one character PR to use the https CRAN mirror instead of the http

### CODE REVIEW

**Comment by sckott** [comment]
thanks!

**Comment by sckott** [comment]
Actually, @csgillespie we should probably switch to using `https://cloud.r-project.org/` - i think that's the global CDN they have and is default for their IDE. Can you make that change?

**Comment by csgillespie** [comment]
Good spot - [List of cran mirrors](https://cran.rstudio.org/mirrors.html). Sorry, I didn't think to check.

**Comment by csgillespie** [comment]
As an aside, a reasonable additional argument to `debian_install_r()`, would be `rprofile` with the default value of `options(repos=c(\'https://cloud.r-project.org/\'))`. 

The rationale is that some people might want to use the RSPM, but you need to be careful with your Ubuntu version. You might also want to tweak  other arguments, e.g. Ncpus in options

Happy to make another PR if you want.

**Comment by sckott** [comment]
Good idea to have a parameter `rprofile` - can you send another PR for that?

**Pull request merged**
