### PR TITLE
Spaces fixes

### LINKED ISSUE #163: Cannot change "spaces_base" variable, spaces different region support
Since spaces can be located in many regions and not only in `nyc3` 
as defined here: https://github.com/sckott/analogsea/blob/8f1f5698df5a58f42d3e22d6a03fc52082de595e/R/spaces.R#L1
we need option to change this spaces_base variable / URL.

As I can currently see that is not possible, please tell me if I am wrong.
Maybe we can also use some env variable like `DO_SPACES_BASE` to specify endpoint?

### PR DESCRIPTION
**Pull request by amoeba**
Kinda-grabbag-of-a-PR here:

aws.s3 got some fixes, not sure if they're on CRAN yet, but now things that broke now work!

- `space_create` works and is now re-enabled
- `spaces_object_put` works w/ multipart
- `spaces_object_delete` works now and is now re-enabled

Also added:

- All regions can now be used via the `DO_SPACES_REGION` env var, to address #163
- Appended a note to vignette about Spaces/Objects. I see your issues about having R help pages in #150 which I agree is an improvement
- Added `space_delete` and `space_list()` which are two API calls we hadn't done

Fixes #163

More to come as I make time!

### CODE REVIEW

**Comment by amoeba** [comment]
Just added space_location and a small fix I missed from R CMD CHECK.

**Comment by sckott** [comment]
Looking good. 

 > Add documentation page at ?spaces_info. Is that the kind of thing you were looking for in #150?

Yeah i think so, looks good. We can see what users are confused by and add more details later. 

Are there other things you're adding here?

**Comment by amoeba** [comment]
All good now! Thanks.

**Comment by sckott** [comment]
@amoeba i can't get `space_create()` to work. I pulled your branch down locally, then `devtools::load_all()`, I had a access key and secret key and then set the region to nyc3, then did 

```r
space_create("new_space_name", config=httr::verbose())
```

```r
-> PUT /new_space_name/ HTTP/1.1
-> Host: nyc3.digitaloceanspaces.com
-> User-Agent: libcurl/7.54.0 r-curl/3.2 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Length: 0
->
<- HTTP/1.1 400 Bad Request
<- Date: Mon, 06 Aug 2018 23:46:23 GMT
<- Content-Length: 153
<- Content-Type: text/plain; charset=utf-8
<-
```

with some headers stripped out for brevity. 

so i'm getting a 400 client error. Does it work for you?

**Comment by amoeba** [comment]
Did you build a copy of aws.s3 from the latest on the `master` branch or are you using the latest CRAN release?

**Comment by sckott** [comment]
used latest from github `0.3.19`

**Comment by amoeba** [comment]
Okay, thanks for testing this out. I'll take a look in the AM and see if I was just hallucinating.

**Comment by sckott** [comment]
thanks

**Comment by amoeba** [comment]
I had a sec just now to test. Works for me. Our implementation doesn't catch any errors `aws.s3` gets into so it's a bit of a pain and could use some work. I wonder what's different between our approaches. Here's mine:

```r
> library(analogsea)
> Sys.setenv("DO_SPACES_REGION"="nyc3",
+            "DO_SPACES_ACCESS_KEY"="...",
+            "DO_SPACES_SECRET_KEY"="...")
> # List my spaces
> spaces()
named list()
> space_create("test-for-scott")
New space test-for-scott created successfully
```

<details>
<summary>Session Info</summary>

```
> devtools::session_info()
Session info -----------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.2.723)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Juneau              
 date     2018-08-06                  

Packages ---------------------------------------------------------------------------------
 package       * version    date       source                         
 analogsea     * 0.6.5.9110 2018-08-07 local                          
 aws.s3          0.3.19     2018-08-07 Github (cloudyr/aws.s3@874f6a7)
 aws.signature   0.4.4      2018-07-27 CRAN (R 3.5.0)                 
 base          * 3.5.1      2018-07-05 local                          
 base64enc       0.1-3      2015-07-28 CRAN (R 3.5.0)                 
 compiler        3.5.1      2018-07-05 local                          
 curl            3.2        2018-03-28 CRAN (R 3.5.0)                 
 datasets      * 3.5.1      2018-07-05 local                          
 devtools        1.13.5     2018-02-18 CRAN (R 3.5.0)                 
 digest          0.6.15     2018-01-28 CRAN (R 3.5.0)                 
 graphics      * 3.5.1      2018-07-05 local                          
 grDevices     * 3.5.1      2018-07-05 local                          
 httr            1.3.1      2017-08-20 CRAN (R 3.5.0)                 
 jsonlite        1.5        2017-06-01 CRAN (R 3.5.0)                 
 magrittr        1.5        2014-11-22 CRAN (R 3.5.0)                 
 memoise         1.1.0      2017-04-21 CRAN (R 3.5.0)                 
 methods       * 3.5.1      2018-07-05 local                          
 mime            0.5        2016-07-07 CRAN (R 3.5.0)                 
 R6              2.2.2      2017-06-17 CRAN (R 3.5.0)                 
 Rcpp            0.12.18    2018-07-23 CRAN (R 3.5.0)                 
 stats         * 3.5.1      2018-07-05 local                          
 tools           3.5.1      2018-07-05 local                          
 utils         * 3.5.1      2018-07-05 local                          
 withr           2.1.2      2018-03-15 CRAN (R 3.5.0)                 
 xml2            1.2.0      2018-01-24 CRAN (R 3.5.0)                 
 yaml            2.2.0      2018-07-25 cran (@2.2.0)
 collate  en_US.UTF-8                 
 tz       America/Juneau              
 date     2018-08-06                  

Packages ---------------------------------------------------------------------------------
 package       * version    date       source        
 analogsea     * 0.6.5.9110 2018-08-07 local         
 aws.s3          0.3.19     2018-08-07 local         
 aws.signature   0.4.1      2018-04-09 CRAN (R 3.5.0)
 base          * 3.5.1      2018-07-05 local         
 base64enc       0.1-3      2015-07-28 CRAN (R 3.5.0)
 compiler        3.5.1      2018-07-05 local         
 curl            3.2        2018-03-28 CRAN (R 3.5.0)
 datasets      * 3.5.1      2018-07-05 local         
 devtools        1.13.5     2018-02-18 CRAN (R 3.5.0)
 digest          0.6.15     2018-01-28 CRAN (R 3.5.0)
 graphics      * 3.5.1      2018-07-05 local         
 grDevices     * 3.5.1      2018-07-05 local         
 httr            1.3.1      2017-08-20 CRAN (R 3.5.0)
 jsonlite        1.5        2017-06-01 CRAN (R 3.5.0)
 magrittr        1.5        2014-11-22 CRAN (R 3.5.0)
 memoise         1.1.0      2017-04-21 CRAN (R 3.5.0)
 methods       * 3.5.1      2018-07-05 local         
 mime            0.5        2016-07-07 CRAN (R 3.5.0)
 R6              2.2.2      2017-06-17 CRAN (R 3.5.0)
 Rcpp            0.12.17    2018-05-18 CRAN (R 3.5.0)
 stats         * 3.5.1      2018-07-05 local         
 tools           3.5.1      2018-07-05 local         
 utils         * 3.5.1      2018-07-05 local         
 withr           2.1.2      2018-03-15 CRAN (R 3.5.0)
 xml2            1.2.0      2018-01-24 CRAN (R 3.5.0)
 yaml            2.2.0      2018-07-25 cran (@2.2.0)
```
</details>

And the space I made shows up on the website just fine. Our our versions of aws.s3 and aws.signature the same?

**Comment by sckott** [comment]
will check, thanks

**Comment by sckott** [comment]
<details> <summary><strong>same versions </strong></summary>

```r
Packages -------------
 package       * version    date       source
 .py             0.0.16     <NA>       local
 analogsea     * 0.6.5.9110 <NA>       local
 aws.s3          0.3.19     2018-08-06 Github (cloudyr/aws.s3@874f6a7)
 aws.signature   0.4.4      2018-07-27 CRAN (R 3.5.1)
 base          * 3.5.1      2018-07-19 local
 base64enc       0.1-3      2015-07-28 CRAN (R 3.5.0)
 commonmark      1.5        2018-04-28 CRAN (R 3.5.0)
 compiler        3.5.1      2018-07-19 local
 curl            3.2        2018-03-28 CRAN (R 3.5.0)
 datasets      * 3.5.1      2018-07-19 local
 devtools        1.13.6     2018-06-27 CRAN (R 3.5.0)
 digest          0.6.15     2018-01-28 CRAN (R 3.5.0)
 graphics      * 3.5.1      2018-07-19 local
 grDevices     * 3.5.1      2018-07-19 local
 httr            1.3.1      2017-08-20 CRAN (R 3.5.0)
 jsonlite        1.5        2017-06-01 CRAN (R 3.5.0)
 magrittr        1.5        2014-11-22 CRAN (R 3.5.0)
 memoise         1.1.0      2017-04-21 CRAN (R 3.5.0)
 methods       * 3.5.1      2018-07-19 local
 R6              2.2.2      2017-06-17 CRAN (R 3.5.0)
 Rcpp            0.12.18    2018-07-23 CRAN (R 3.5.1)
 rlang           0.2.1      2018-05-30 CRAN (R 3.5.0)
 roxygen2        6.1.0      2018-07-27 CRAN (R 3.5.0)
 rstudioapi      0.7        2017-09-07 CRAN (R 3.5.0)
 rtichoke        0.2.1      <NA>       local
 ssh             0.2        2018-06-04 CRAN (R 3.5.0)
 stats         * 3.5.1      2018-07-19 local
 stringi         1.2.4      2018-07-20 CRAN (R 3.5.0)
 stringr         1.3.1      2018-05-10 CRAN (R 3.5.0)
 testthat      * 2.0.0      2017-12-13 CRAN (R 3.5.0)
 tools           3.5.1      2018-07-19 local
 utils         * 3.5.1      2018-07-19 local
 withr           2.1.2      2018-03-15 CRAN (R 3.5.0)
 xml2            1.2.0      2018-01-24 CRAN (R 3.5.0)
 yaml            2.2.0      2018-07-25 CRAN (R 3.5.1)
```
</details>

Still not workfing for me, can you do `space_create()` with `config=httr::verbose()` so I can see the curl details?  I'm getting a 400 but because aws.s3 just returns NULL on an error and doesn't pass on the response body I can't see what the message is, a downside of depending on this external pkg

**Comment by amoeba** [comment]
Here's the doubly-verbose output:

```
> space_create("test-for-scott", config=httr::verbose(), verbose = TRUE)
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using user-supplied value for AWS Region ('nyc3')
Non-AWS base URL requested.
S3 Request URL: https://nyc3.digitaloceanspaces.com/test-for-scott/
Executing request with AWS credentials
Checking for credentials in user-supplied values
Using user-supplied value for AWS Access Key ID
Using user-supplied value for AWS Secret Access Key
Using user-supplied value for AWS Region ('nyc3')
Checking for credentials in user-supplied values
Using user-supplied value for AWS Secret Access Key
Using user-supplied value for AWS Region ('nyc3')
-> PUT /test-for-scott/ HTTP/1.1
-> Host: nyc3.digitaloceanspaces.com
-> User-Agent: libcurl/7.54.0 r-curl/3.2 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> x-amz-acl: private
-> x-amz-date: 20180807T201511Z
-> x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
-> Authorization: AWS4-HMAC-SHA256 Credential=P4UB7DRO2X7VX2UV47LN/20180807/nyc3/s3/aws4_request, SignedHeaders=host;x-amz-acl;x-amz-date, Signature=85381e20229d9359ad4361b2b3929074c1cc52ea86e269d7c17af627dc772729
-> Content-Length: 0
-> 
<- HTTP/1.1 200 OK
<- Date: Tue, 07 Aug 2018 20:15:11 GMT
<- Content-Length: 0
<- 
Parsing AWS API response
Success: (200) OK
New space test-for-scott created successfully
```

I've found debugging by throwing `browser()` statements in `s3HTTP` which does most of the work. I'm scratching my head trying to think how I can help debug further.

**Comment by sckott** [comment]
hugh, seems that I was running into invalid regions

https://www.digitalocean.com/docs/platform/availability-matrix/#product-availability-by-datacenter-region suggests nyc3 is not available, with the following avail: ams3, sfo2, sgp1

i imagine we should change the default to one of those 3?

**Comment by amoeba** [comment]
> i imagine we should change the default to one of those 3?

I think this is just due to today's spaces outage, and I think it might fix itself. IIRC nyc3 was the first and only availability region and I haven't ehard anything that indicates it's going away. 
Screen Shot 2019-03-20 at 4 16 33 PM

Incident details: https://status.digitalocean.com/incidents/bbyt03t1vm88

I'll do some digging.

**Comment by sckott** [comment]
hmm, if that's right that nyc3 is just out temporarily, then I guess I don't know why it was failing on my end before. Anyway, seems to be working now

**Comment by sckott** [comment]
i can work on https://github.com/sckott/analogsea/issues/150 and then I think we're very close to getting this off to cran

**Comment by amoeba** [comment]
Sounds great, let me know if you want a hand or a second set of eyes.

**Pull request merged**
